language: cpp

env:
  global:
    - LINUX_DIST=trusty
    - CXX_FLAGS="-Wall -Wextra -Wpedantic" # -Werror

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - libboost1.55-all-dev
            - gcc-4.9
            - clang-3.7
            - cmake-data
            - cmake

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

script:
  - mkdir -p build.gcc-4.9
  - cd build.gcc-4.9
  - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - make
