language: cpp

env:
  global:
    - LINUX_DIST=trusty
    - CXX_FLAGS="-Wall -Wextra -Wpedantic" # -Werror
    - MAKE_FLAGS="-j2"

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - libboost-program-options-dev
            - mpi-default-dev
            - g++-4.9
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"            
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libboost1.55-all-dev
            - clang-3.7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
  - eval "${MATRIX_EVAL}"

script:
  - which ${CC}
  - which ${CXX}
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - make
