matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  
    script:
      - mkdir build.gcc-4.9
      - cd build.gcc-4.9
      - cmake ..
      - make
